name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  get_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: "postgres/postgres.git"
        ref: 'master'
    - name: 'get meson'
      run: |
        python -m pip install meson
        python -m pip install ninja
    - name : 'build postgres'
      run: |
        cd postgres
        meson setup build
        cd build
        ninja
        
